/* eslint-disable @next/next/no-img-element */
import { Building2, FileText } from "lucide-react";
import type { BrandRecord } from "@/features/admin-api/server/admin-api";
import { DeleteBrandButton } from "@/features/admin-brands/components/DeleteBrandButton";
import { EditBrandDialog } from "@/features/admin-brands/components/EditBrandDialog";

export function BrandsTable({ brands }: Readonly<{ brands: BrandRecord[] }>) {
  if (brands.length === 0) return <div className="rounded-xl border border-dashed border-outline-variant bg-surface-container-low p-10 text-center"><Building2 aria-hidden="true" className="mx-auto size-9 text-outline" /><h2 className="mt-3 text-headline-sm font-semibold text-on-surface">Chưa có thương hiệu nào</h2><p className="mt-1 text-body-md text-on-surface-variant">Thêm thương hiệu đầu tiên để dùng trong danh mục sản phẩm.</p></div>;

  return <div className="overflow-x-auto rounded-xl border border-outline-variant/30 bg-surface-container-lowest shadow-sm"><table className="w-full min-w-[840px] border-collapse text-left"><caption className="sr-only">Danh sách thương hiệu ThanhDanh-VMC</caption><thead className="bg-surface-container-low text-label-sm font-semibold uppercase tracking-wide text-on-surface-variant"><tr><th className="px-5 py-3">Logo</th><th className="px-5 py-3">Thương hiệu</th><th className="px-5 py-3">Mô tả</th><th className="px-5 py-3">Mã định danh</th><th className="px-5 py-3"><span className="sr-only">Thao tác</span></th></tr></thead><tbody className="divide-y divide-outline-variant/20">{brands.map((brand) => <tr key={brand.id} className="transition hover:bg-surface-container-low"><td className="px-5 py-4">{brand.imageUrl ? <img src={brand.imageUrl} alt={`Logo ${brand.name}`} className="size-12 rounded-lg border border-outline-variant/20 bg-white object-contain p-1" /> : <span className="flex size-12 items-center justify-center rounded-lg bg-primary-fixed text-primary"><Building2 aria-hidden="true" className="size-6" /></span>}</td><td className="px-5 py-4"><p className="font-semibold text-on-surface">{brand.name}</p></td><td className="max-w-xl px-5 py-4 text-body-md leading-6 text-on-surface-variant">{brand.description || <span className="inline-flex items-center gap-1.5 text-outline"><FileText aria-hidden="true" className="size-4" />Chưa có mô tả</span>}</td><td className="px-5 py-4 font-mono text-body-sm text-primary">{brand.id}</td><td className="px-5 py-4"><div className="flex items-center"><EditBrandDialog brand={brand} /><DeleteBrandButton id={brand.id} name={brand.name} /></div></td></tr>)}</tbody></table></div>;
}
