import { Filter, Search } from "lucide-react";
import type { SelectOption } from "@/features/admin-api/server/admin-api";

type ProductFiltersProps = Readonly<{ categories: SelectOption[]; brands: SelectOption[]; search: string; categoryId?: string; brandId?: string }>;

/** GET form keeps filters shareable in the URL and renders without client JavaScript. */
export function ProductFilters({ categories, brands, search, categoryId, brandId }: ProductFiltersProps) {
  return <form action="/admin/san-pham" className="grid gap-3 rounded-xl bg-surface-container-low p-4 md:grid-cols-2 xl:grid-cols-4"><label className="relative"><span className="sr-only">Tìm kiếm sản phẩm</span><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-outline" /><input name="search" defaultValue={search} placeholder="Tên, SKU hoặc mã sản phẩm" className="w-full rounded-lg bg-surface-container-lowest py-2.5 pl-9 pr-3 text-body-md outline-none ring-1 ring-outline-variant/30 focus:ring-primary" /></label><label><span className="sr-only">Lọc theo danh mục</span><select name="categoryId" defaultValue={categoryId ?? ""} className="w-full rounded-lg bg-surface-container-lowest px-3 py-2.5 text-body-md outline-none ring-1 ring-outline-variant/30 focus:ring-primary"><option value="">Tất cả danh mục</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label><span className="sr-only">Lọc theo hãng</span><select name="brandId" defaultValue={brandId ?? ""} className="w-full rounded-lg bg-surface-container-lowest px-3 py-2.5 text-body-md outline-none ring-1 ring-outline-variant/30 focus:ring-primary"><option value="">Tất cả thương hiệu</option>{brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</select></label><button type="submit" className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-label-md font-semibold text-on-primary transition hover:bg-primary-container"><Filter aria-hidden="true" className="size-4" />Áp dụng bộ lọc</button></form>;
}
