import { Send } from "lucide-react";
import { Reveal } from "@/components/motion/Reveal";

/** Static GET form; it is ready to connect to an RFQ route or backend in a later phase. */
export function ContactCtaSection() {
  return (
    <section id="bao-gia" className="mx-auto max-w-7xl px-gutter py-20"><Reveal><div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-primary to-primary-container p-7 text-on-primary shadow-2xl sm:p-12"><div aria-hidden="true" className="absolute -bottom-24 -right-20 size-80 rounded-full bg-secondary/25 blur-3xl" /><div className="relative max-w-3xl"><span className="inline-flex rounded-full bg-white/10 px-3 py-1 text-label-sm font-semibold backdrop-blur-sm">Hỗ trợ nhanh 24/7</span><h2 className="mt-4 text-headline-lg font-bold">Bạn cần tư vấn kỹ thuật hoặc báo giá thiết bị thủy lực?</h2><p className="mt-4 text-body-lg leading-7 text-on-primary/90">Gửi thông số kỹ thuật hoặc mã thiết bị. Kỹ sư CTY ThanhDanh-VMC sẽ phản hồi phương án và báo giá chi tiết.</p><form action="/yeu-cau-bao-gia" method="get" className="mt-8 grid gap-3 sm:grid-cols-3"><label className="sr-only" htmlFor="name">Họ tên hoặc công ty</label><input id="name" name="name" required placeholder="Họ và tên / Công ty" className="min-w-0 rounded-xl bg-surface px-4 py-3 text-body-md text-on-surface outline-none ring-2 ring-transparent placeholder:text-outline focus:ring-secondary-fixed" /><label className="sr-only" htmlFor="contact">Số điện thoại hoặc email</label><input id="contact" name="contact" required placeholder="Số điện thoại / Email" className="min-w-0 rounded-xl bg-surface px-4 py-3 text-body-md text-on-surface outline-none ring-2 ring-transparent placeholder:text-outline focus:ring-secondary-fixed" /><button type="submit" className="inline-flex items-center justify-center gap-2 rounded-xl bg-secondary-container px-5 py-3 text-label-md font-semibold text-on-secondary-container shadow-lg transition-colors hover:bg-secondary-fixed"><Send className="size-4" />Gửi yêu cầu</button></form></div></div></Reveal></section>
  );
}
