import type { Metadata } from "next";
import Link from "next/link";
import { ChevronRight } from "lucide-react";
import { FilterSidebar } from "@/features/catalog/components/FilterSidebar";
import { Pagination } from "@/features/catalog/components/Pagination";
import { ProductGrid } from "@/features/catalog/components/ProductGrid";
import { catalogProducts } from "@/features/catalog/data/catalog-data";

export const metadata: Metadata = { title: "Danh mục sản phẩm | CTY ThanhDanh-VMC", description: "Khám phá thiết bị thủy lực, trạm nguồn, van điều khiển, xi lanh và phụ tùng công nghiệp từ CTY ThanhDanh-VMC." };

export default function ProductCatalogPage() {
  return (
    <><section className="bg-surface-container-low px-gutter py-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="flex items-center gap-1 text-body-sm text-on-surface-variant"><Link href="/" className="hover:text-primary">Trang chủ</Link><ChevronRight className="size-4" /><span className="font-medium text-primary">Sản phẩm</span></nav><div className="mt-5 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="text-label-sm font-semibold uppercase tracking-wider text-primary">Danh mục thiết bị công nghiệp</p><h1 className="mt-2 text-headline-lg font-bold text-on-surface">Thiết bị Thủy lực Chính hãng &amp; Phụ tùng Công nghiệp</h1></div><div className="flex items-center gap-3"><span className="text-body-md text-on-surface-variant">Hiển thị 1–9 của 48 sản phẩm</span><select aria-label="Sắp xếp sản phẩm" defaultValue="default" className="rounded-xl border border-outline-variant/30 bg-surface px-3 py-2 text-body-md text-on-surface outline-none focus:border-primary"><option value="default">Sắp xếp: Mặc định</option><option value="pressure-desc">Áp suất: Cao đến thấp</option><option value="flow-asc">Lưu lượng: Tăng dần</option><option value="newest">Mới nhất</option></select></div></div></div></section><section className="mx-auto max-w-7xl px-gutter py-12"><div className="grid gap-8 lg:grid-cols-4"><FilterSidebar /><div className="min-w-0 lg:col-span-3"><ProductGrid products={catalogProducts} /><Pagination /></div></div></section><section className="bg-surface-container-low px-gutter py-16"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-label-sm font-semibold uppercase tracking-wider text-primary">Tài liệu kỹ thuật &amp; Hướng dẫn</p><h2 className="mt-2 text-headline-md font-bold text-on-surface">Cẩm Nang Lựa Chọn Thiết Bị Thủy Lực Cho Ứng Dụng Công Nghiệp Nặng</h2><p className="mt-4 text-body-lg leading-7 text-on-surface-variant">Lựa chọn đúng hệ thống truyền động thủy lực quyết định hiệu suất vận hành, tuổi thọ thiết bị và mức tiêu thụ năng lượng của toàn bộ dây chuyền.</p></div><div className="mt-8 grid gap-6 md:grid-cols-3">{[["1. Xác định áp suất làm việc", "Tính toán hệ số an toàn phù hợp tải trọng và lựa chọn thiết bị đáp ứng dải áp vận hành."], ["2. Tính lưu lượng & tốc độ", "Lưu lượng bơm quyết định tốc độ cơ cấu chấp hành và hiệu suất năng lượng toàn hệ thống."], ["3. Kiểm tra tiêu chuẩn CO/CQ", "Ưu tiên thiết bị có nguồn gốc rõ ràng, chứng chỉ chất lượng và dịch vụ kỹ thuật sau bán hàng."]].map(([title, description]) => <article key={title} className="rounded-xl bg-surface-container-lowest p-6 shadow-sm"><h3 className="text-headline-sm font-semibold text-on-surface">{title}</h3><p className="mt-3 text-body-md leading-6 text-on-surface-variant">{description}</p></article>)}</div></div></section></>
  );
}
