/* eslint-disable @next/next/no-img-element */
import { FileText, FolderTree } from "lucide-react";
import type { CategoryRecord } from "@/features/admin-api/server/admin-api";
import { DeleteCategoryButton } from "@/features/admin-categories/components/DeleteCategoryButton";
import { EditCategoryDialog } from "@/features/admin-categories/components/EditCategoryDialog";

export function CategoriesTable({ categories }: Readonly<{ categories: CategoryRecord[] }>) {
  if (categories.length === 0) return <div className="rounded-xl border border-dashed border-outline-variant bg-surface-container-low p-10 text-center"><FolderTree aria-hidden="true" className="mx-auto size-9 text-outline" /><h2 className="mt-3 text-headline-sm font-semibold text-on-surface">Chưa có danh mục nào</h2><p className="mt-1 text-body-md text-on-surface-variant">Thêm danh mục để tổ chức catalogue thiết bị.</p></div>;

  return <div className="overflow-x-auto rounded-xl border border-outline-variant/30 bg-surface-container-lowest shadow-sm"><table className="w-full min-w-[840px] border-collapse text-left"><caption className="sr-only">Danh sách danh mục ThanhDanh-VMC</caption><thead className="bg-surface-container-low text-label-sm font-semibold uppercase tracking-wide text-on-surface-variant"><tr><th className="px-5 py-3">Hình ảnh</th><th className="px-5 py-3">Danh mục</th><th className="px-5 py-3">Mô tả</th><th className="px-5 py-3">Mã định danh</th><th className="px-5 py-3"><span className="sr-only">Thao tác</span></th></tr></thead><tbody className="divide-y divide-outline-variant/20">{categories.map((category) => <tr key={category.id} className="transition hover:bg-surface-container-low"><td className="px-5 py-4">{category.imageUrl ? <img src={category.imageUrl} alt={`Ảnh ${category.name}`} className="size-12 rounded-lg border border-outline-variant/20 bg-white object-cover" /> : <span className="flex size-12 items-center justify-center rounded-lg bg-primary-fixed text-primary"><FolderTree aria-hidden="true" className="size-6" /></span>}</td><td className="px-5 py-4"><p className="font-semibold text-on-surface">{category.name}</p></td><td className="max-w-xl px-5 py-4 text-body-md leading-6 text-on-surface-variant">{category.description || <span className="inline-flex items-center gap-1.5 text-outline"><FileText aria-hidden="true" className="size-4" />Chưa có mô tả</span>}</td><td className="px-5 py-4 font-mono text-body-sm text-primary">{category.id}</td><td className="px-5 py-4"><div className="flex items-center"><EditCategoryDialog category={category} /><DeleteCategoryButton id={category.id} name={category.name} /></div></td></tr>)}</tbody></table></div>;
}
